---
abstract: 'Interact with LogicBoxes reseller API'
author:
  - 'Robert Stone <drzigman@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Test::More: 0
  Test::Most: 0
  Test::Requires: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300009, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-LogicBoxes
no_index:
  namespace:
    - WWW::LogicBoxes::Role::Commands
requires:
  Any::Moose: 0
  Carp: 0
  Data::Dumper: 0
  English: 0
  HTTP::Tiny: 0
  IO::Socket::SSL: 0
  URI::Escape: 0
  XML::LibXML::Simple: 0
  perl: v5.10.0
resources:
  bugtracker: https://github.com/drzigman/www-logicboxes/issues
  homepage: http://search.cpan.org/dist/WWW-LogicBoxes
  repository: git://github.com/drzigman/www-logicboxes.git
version: 0.0.3
